{-# LANGUAGE CPP #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif
{-# LANGUAGE FlexibleInstances #-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for PrintCpp.
--   Generated by the BNF converter.

module PrintCpp where

import qualified AbsCpp
import Data.Char

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else ' ':s)

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsCpp.Id where
  prt _ (AbsCpp.Id i) = doc (showString i)

instance Print AbsCpp.Program where
  prt i e = case e of
    AbsCpp.PDefs defs -> prPrec i 0 (concatD [prt 0 defs])

instance Print AbsCpp.Def where
  prt i e = case e of
    AbsCpp.DFun type_ tokenid args stms -> prPrec i 0 (concatD [prt 0 type_, prt 0 tokenid, doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "{"), prt 0 stms, doc (showString "}")])
    AbsCpp.DUserFun tokenid1 tokenid2 args stms -> prPrec i 0 (concatD [prt 0 tokenid1, prt 0 tokenid2, doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "{"), prt 0 stms, doc (showString "}")])
    AbsCpp.DUSing exp -> prPrec i 0 (concatD [doc (showString "using"), prt 15 exp, doc (showString ";")])
    AbsCpp.DType type_1 tokenid type_2 -> prPrec i 0 (concatD [prt 0 type_1, prt 0 tokenid, doc (showString "("), prt 0 type_2, doc (showString ")"), doc (showString ";")])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsCpp.Def] where
  prt = prtList

instance Print AbsCpp.Arg where
  prt i e = case e of
    AbsCpp.ADecl type_ tokenid -> prPrec i 0 (concatD [prt 0 type_, prt 0 tokenid])
    AbsCpp.ASingT type_ types -> prPrec i 0 (concatD [prt 0 type_, doc (showString "<"), prt 0 types, doc (showString ">"), doc (showString "&")])
    AbsCpp.ASingR tokenid -> prPrec i 0 (concatD [doc (showString "const"), prt 0 tokenid, doc (showString "&")])
    AbsCpp.AStreamR tokenid1 tokenid2 -> prPrec i 0 (concatD [prt 0 tokenid1, doc (showString "&"), prt 0 tokenid2])
    AbsCpp.AConstT type_ tokenid -> prPrec i 0 (concatD [doc (showString "const"), prt 0 type_, doc (showString "&"), prt 0 tokenid])
    AbsCpp.AConst type_ tokenid -> prPrec i 0 (concatD [doc (showString "const"), prt 0 type_, prt 0 tokenid])
    AbsCpp.AConstR tokenid1 tokenid2 -> prPrec i 0 (concatD [doc (showString "const"), prt 0 tokenid1, doc (showString "&"), prt 0 tokenid2])
    AbsCpp.AConstL typelist tokenid -> prPrec i 0 (concatD [doc (showString "const"), prt 0 typelist, prt 0 tokenid])
    AbsCpp.AConstLR typelist tokenid -> prPrec i 0 (concatD [doc (showString "const"), prt 0 typelist, doc (showString "&"), prt 0 tokenid])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsCpp.Arg] where
  prt = prtList

instance Print AbsCpp.Stm where
  prt i e = case e of
    AbsCpp.STDef typedef -> prPrec i 0 (concatD [prt 0 typedef, doc (showString ";")])
    AbsCpp.SExp exp -> prPrec i 0 (concatD [prt 0 exp, doc (showString ";")])
    AbsCpp.SDecls type_ tokenids -> prPrec i 0 (concatD [prt 0 type_, prt 0 tokenids, doc (showString ";")])
    AbsCpp.SDecls2 exp tokenids -> prPrec i 0 (concatD [prt 15 exp, prt 0 tokenids, doc (showString ";")])
    AbsCpp.SConst type_ tokenids -> prPrec i 0 (concatD [doc (showString "const"), prt 0 type_, prt 0 tokenids, doc (showString ";")])
    AbsCpp.SInit type_ tokenids exp -> prPrec i 0 (concatD [prt 0 type_, prt 0 tokenids, doc (showString "="), prt 0 exp, doc (showString ";")])
    AbsCpp.SInit2 exp1 tokenids exp2 -> prPrec i 0 (concatD [prt 15 exp1, prt 0 tokenids, doc (showString "="), prt 0 exp2, doc (showString ";")])
    AbsCpp.SReturn exp -> prPrec i 0 (concatD [doc (showString "return"), prt 0 exp, doc (showString ";")])
    AbsCpp.SReturnVoid -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    AbsCpp.SWhile exp stm -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm])
    AbsCpp.SBlock stms -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stms, doc (showString "}")])
    AbsCpp.SIf exp stm -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm])
    AbsCpp.SIfElse exp stm1 stm2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 exp, doc (showString ")"), prt 0 stm1, doc (showString "else"), prt 0 stm2])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print [AbsCpp.Stm] where
  prt = prtList

instance Print AbsCpp.Exp where
  prt i e = case e of
    AbsCpp.ETrue -> prPrec i 15 (concatD [doc (showString "true")])
    AbsCpp.EFalse -> prPrec i 15 (concatD [doc (showString "false")])
    AbsCpp.EInt n -> prPrec i 15 (concatD [prt 0 n])
    AbsCpp.EDouble d -> prPrec i 15 (concatD [prt 0 d])
    AbsCpp.EString strs -> prPrec i 15 (concatD [prt 0 strs])
    AbsCpp.EId tokenid -> prPrec i 15 (concatD [prt 0 tokenid])
    AbsCpp.EType type_ -> prPrec i 15 (concatD [prt 0 type_])
    AbsCpp.EApp tokenid exps -> prPrec i 15 (concatD [prt 0 tokenid, doc (showString "("), prt 0 exps, doc (showString ")")])
    AbsCpp.EQConst exp1 exp2 -> prPrec i 15 (concatD [prt 15 exp1, doc (showString "::"), prt 15 exp2])
    AbsCpp.EInd exp exps -> prPrec i 15 (concatD [prt 15 exp, doc (showString "["), prt 0 exps, doc (showString "]")])
    AbsCpp.EPIncr exp -> prPrec i 14 (concatD [prt 15 exp, doc (showString "++")])
    AbsCpp.EPDecr exp -> prPrec i 14 (concatD [prt 15 exp, doc (showString "--")])
    AbsCpp.EDot exp1 exp2 -> prPrec i 14 (concatD [prt 14 exp1, doc (showString "."), prt 15 exp2])
    AbsCpp.ENega exp -> prPrec i 13 (concatD [doc (showString "!"), prt 14 exp])
    AbsCpp.EIncr exp -> prPrec i 13 (concatD [doc (showString "++"), prt 14 exp])
    AbsCpp.EDecr exp -> prPrec i 13 (concatD [doc (showString "--"), prt 14 exp])
    AbsCpp.ETimes exp1 exp2 -> prPrec i 12 (concatD [prt 12 exp1, doc (showString "*"), prt 13 exp2])
    AbsCpp.EDiv exp1 exp2 -> prPrec i 12 (concatD [prt 12 exp1, doc (showString "/"), prt 13 exp2])
    AbsCpp.EMod exp1 exp2 -> prPrec i 12 (concatD [prt 12 exp1, doc (showString "%"), prt 13 exp2])
    AbsCpp.EPlus exp1 exp2 -> prPrec i 11 (concatD [prt 11 exp1, doc (showString "+"), prt 12 exp2])
    AbsCpp.EMinus exp1 exp2 -> prPrec i 11 (concatD [prt 11 exp1, doc (showString "-"), prt 12 exp2])
    AbsCpp.ELShift exp1 exp2 -> prPrec i 10 (concatD [prt 10 exp1, doc (showString "<<"), prt 11 exp2])
    AbsCpp.ERShift exp1 exp2 -> prPrec i 10 (concatD [prt 15 exp1, doc (showString ">>"), prt 10 exp2])
    AbsCpp.ELt exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString "<"), prt 10 exp2])
    AbsCpp.EGt exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString ">"), prt 10 exp2])
    AbsCpp.ELtEq exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString "<="), prt 10 exp2])
    AbsCpp.EGtEq exp1 exp2 -> prPrec i 9 (concatD [prt 9 exp1, doc (showString ">="), prt 10 exp2])
    AbsCpp.EEq exp1 exp2 -> prPrec i 8 (concatD [prt 8 exp1, doc (showString "=="), prt 9 exp2])
    AbsCpp.ENEq exp1 exp2 -> prPrec i 8 (concatD [prt 8 exp1, doc (showString "!="), prt 9 exp2])
    AbsCpp.EAnd exp1 exp2 -> prPrec i 4 (concatD [prt 4 exp1, doc (showString "&&"), prt 5 exp2])
    AbsCpp.EOr exp1 exp2 -> prPrec i 3 (concatD [prt 3 exp1, doc (showString "||"), prt 4 exp2])
    AbsCpp.EAss exp1 exp2 -> prPrec i 2 (concatD [prt 3 exp1, doc (showString "="), prt 2 exp2])
    AbsCpp.ECond exp1 exp2 exp3 -> prPrec i 1 (concatD [prt 0 exp1, doc (showString "?"), prt 3 exp2, doc (showString ":"), prt 3 exp3])
    AbsCpp.EExcept exp -> prPrec i 2 (concatD [doc (showString "throw"), prt 0 exp])
    AbsCpp.ETyped exp type_ -> prPrec i 15 (concatD [doc (showString "("), prt 0 exp, doc (showString ":"), prt 0 type_, doc (showString ")")])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsCpp.Exp] where
  prt = prtList

instance Print [AbsCpp.Type] where
  prt = prtList

instance Print [AbsCpp.TokenId] where
  prt = prtList

instance Print [String] where
  prt = prtList

instance Print AbsCpp.Type where
  prt i e = case e of
    AbsCpp.Type_bool -> prPrec i 0 (concatD [doc (showString "bool")])
    AbsCpp.Type_int -> prPrec i 0 (concatD [doc (showString "int")])
    AbsCpp.Type_double -> prPrec i 0 (concatD [doc (showString "double")])
    AbsCpp.Type_void -> prPrec i 0 (concatD [doc (showString "void")])
    AbsCpp.Type_string -> prPrec i 0 (concatD [doc (showString "string")])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print AbsCpp.TypeDef where
  prt i e = case e of
    AbsCpp.TDef exps tokenid -> prPrec i 0 (concatD [doc (showString "typedef"), prt 0 exps, prt 0 tokenid])

instance Print AbsCpp.TypeList where
  prt i e = case e of
    AbsCpp.TList tokenid types -> prPrec i 0 (concatD [prt 0 tokenid, doc (showString "<"), prt 0 types, doc (showString ">")])

instance Print AbsCpp.TokenId where
  prt i e = case e of
    AbsCpp.TId typelist -> prPrec i 0 (concatD [prt 0 typelist])
    AbsCpp.TId2 id -> prPrec i 0 (concatD [prt 0 id])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

