module SkelCpp where

-- Haskell module generated by the BNF converter

import AbsCpp
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transId :: Id -> Result
transId x = case x of
  Id string -> failure x
transProgram :: Program -> Result
transProgram x = case x of
  PDefs defs -> failure x
transDef :: Def -> Result
transDef x = case x of
  DFunc type_ id args stms -> failure x
  DInlineS type_ id args stms -> failure x
  DInlineF type_ id args -> failure x
  DDecl type_ ids -> failure x
  DUsing qconst -> failure x
  DStruct type_ id types -> failure x
  DMain type_ args stms -> failure x
transArg :: Arg -> Result
transArg x = case x of
  ADecl type_ id -> failure x
transStm :: Stm -> Result
transStm x = case x of
  SExp exp -> failure x
  SDecls type_ ids -> failure x
  SInit type_ id exp -> failure x
  SReturn exp -> failure x
  SReturnVoid -> failure x
  SWhile exp stm -> failure x
  SFor stm1 exp1 exp2 stm2 -> failure x
  SDoWhile stm exp -> failure x
  SBlock stms -> failure x
  SIf exp stm -> failure x
  SIfElse exp stm1 stm2 -> failure x
  SMethod type_ id args stm -> failure x
transType :: Type -> Result
transType x = case x of
  TInt -> failure x
  TBool -> failure x
  TVoid -> failure x
  TChar -> failure x
  TDouble -> failure x
  TQConst qconst -> failure x
  TCons type_ -> failure x
  TDef type_ -> failure x
  TRef type_ -> failure x
transQConst :: QConst -> Result
transQConst x = case x of
  QConst names -> failure x
transName :: Name -> Result
transName x = case x of
  NameId id -> failure x
  NTempl id types -> failure x
transExp :: Exp -> Result
transExp x = case x of
  ETrue -> failure x
  EFalse -> failure x
  EInt integer -> failure x
  EDouble double -> failure x
  EString string -> failure x
  EChar char -> failure x
  EQConst qconst -> failure x
  EIdx exp1 exp2 -> failure x
  EApp exp exps -> failure x
  EDot exp1 exp2 -> failure x
  EPIncr exp -> failure x
  EPDecr exp -> failure x
  EDeref exp -> failure x
  EProj exp1 exp2 -> failure x
  EIncr exp -> failure x
  EDecr exp -> failure x
  ENot exp -> failure x
  ETimes exp1 exp2 -> failure x
  EDiv exp1 exp2 -> failure x
  EMod exp1 exp2 -> failure x
  EPlus exp1 exp2 -> failure x
  EMinus exp1 exp2 -> failure x
  EShftL exp exps -> failure x
  EShftR exp1 exp2 -> failure x
  ELt exp1 exp2 -> failure x
  EGt exp1 exp2 -> failure x
  ELtEq exp1 exp2 -> failure x
  EGtEq exp1 exp2 -> failure x
  EEq exp1 exp2 -> failure x
  ENEq exp1 exp2 -> failure x
  EAnd exp1 exp2 -> failure x
  EOr exp1 exp2 -> failure x
  EAss exp1 exp2 -> failure x
  EAssA exp1 exp2 -> failure x
  EAssM exp1 exp2 -> failure x
  EIf exp1 exp2 exp3 -> failure x
  EThrow exp -> failure x
  ETyped exp type_ -> failure x

